import './globals.css'
import  Navbar from "../app/components/Navbar"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="corporate">
      <body>
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}


